language: elixir
elixir:
  - 1.4.2
otp_release:
  - 19.0.0

sudo: required
dist: trusty
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
    # - libwxbase2.8-0
    # - libwxgtk2.8-0
    # - bc
    # - clang-3.7
    # - g++-5
    # - gcc-5
    # - libssl-dev
    # - libsctp1
    # - libnl-dev
    # - libmnl-dev
    # - libsdl2-dev
    # - libsdl-dev
    # - libglew-dev
    # - libglm-dev

env:
  global:
  - ELIXIR_VERSION=1.4.1 ERLANG_VERSION=19.2
before_install:
script:
- sudo apt-get install -qq linux-headers-`uname -r`
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
- scripts/tty0tty.sh
- mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez --force
- elixir scripts/generate_makefile.exs
- make travis_test
