# config/application.yml
defaults: &defaults
  mqtt_url:     'localhost'
  mqtt_port:    1883
  webapp_url:   'my.farmbot.io'
  serial_ports:
    - "/dev/ttyUSB0"
    - "/dev/ttyACM0"

development:
  <<: *defaults
  webapp_url:  'localhost:3000'

test:
  <<: *defaults

production:
  <<: *defaults
