# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.5
    environment:
      MIX_ENV: test

    install_hex_rebar: &install_hex_rebar
      run:
        name: Install hex and rebar
        command: |
          mix local.hex --force
          mix local.rebar --force

    install_nerves_bootstrap: &install_nerves_bootstrap
      run:
        name: Install nerves_bootstrap
        command: mix archive.install hex nerves_bootstrap --force

    working_directory: ~/repo
    steps:
      - checkout
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap

      # specify any bash command here prefixed with `run: `
      - run: mix deps.get
      - run: mix test
