version: 2.0
defaults: &defaults
  docker:
    - image: nervesproject/nerves:0.13.5

install_elixir: &install_elixir
  run:
    name: Install Elixir
    command: |
      wget https://github.com/elixir-lang/elixir/releases/download/v1.5.1/Precompiled.zip
      unzip -d /usr/local/elixir Precompiled.zip
      echo 'export PATH=/usr/local/elixir/bin:$PATH' >> $BASH_ENV

jobs:
  test:
    <<: *defaults
    environment:
      MIX_ENV: test
    steps:
      - checkout
      - <<: *install_elixir
      - restore_cache:
          keys:
            - v3-dependency-cache-{{ checksum "mix.lock.host" }}
            - v3-dependency-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix archive.install hex nerves_bootstrap --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - save_cache:
          key: v3-dependency-cache-{{ checksum "mix.lock.host" }}
          paths:
            - _build
            - deps
            - ~/.mix
            - ~/.nerves
      - run:
          command: mix coveralls.circle

  firmware:
    <<: *defaults
    environment:
      MIX_TARGET: rpi3
      ENV: CI
    steps:
      - checkout
      - <<: *install_elixir
      - restore_cache:
          keys:
            - v3-dependency-cache-{{ checksum "mix.lock.rpi3" }}
            - v3-dependency-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix archive.install hex nerves_bootstrap --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run:
          command: mix firmware
      - save_cache:
          key: v3-dependency-cache-{{ checksum "mix.lock.rpi3" }}
          paths:
            - _build
            - deps
            - ~/.mix
            - ~/.nerves
      - run:
          command: mix firmware.slack --channels C58DCU4A3

workflows:
  version: 2
  test_firmware_upload:
    jobs:
      - test:
          context: org-global
      - firmware:
          context: org-global
  deploy_nightly:
    environment:
      MIX_ENV: prod
      MIX_TARGET: rpi3
    jobs:
      - firmware:
          context: org-global
          filters:
            branches:
              only: nightly
