---
defaults:
  secrets_file: secrets.txt
  mqtt_url: localhost
  mqtt_port: 1883
  webapp_url: my.farmbot.io
  serial_ports: &1
  - "/dev/ttyUSB0"
  - "/dev/ttyACM0"
development:
  secrets_file: secrets.txt
  mqtt_url: localhost
  mqtt_port: 1883
  webapp_url: localhost:3000
  serial_ports: *1
test:
  secrets_file: secrets.txt
  mqtt_url: localhost
  mqtt_port: 1883
  webapp_url: my.farmbot.io
  serial_ports: *1
production:
  secrets_file: secrets.txt
  mqtt_url: localhost
  mqtt_port: 1883
  webapp_url: my.farmbot.io
  serial_ports:
  - "/dev/ttyUSB0"
  - "/dev/ttyACM0"
  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE0NTg5Mjk3NDUsImp0aSI6IjJmMmQ4MmQ3LTIyMDgtNGY0OC1hZjg3LTY1ODk3M2FjMjMzNSIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMC8iLCJleHAiOjE0NTkyNzUzNDUsIm1xdHQiOiJsb2NhbGhvc3QifQ.qhdjWXsSdqbe4jOYY9G4f61Izfebo2lpnxAhJxo7pC7T-B6g2WlO2kaZ0hFL68DV7NiUReoaV0HXlTKIqhCO2yDW4HOkvyDk6_0OVPxTetX8e-gBYfu-ErQ9MoLjFNp7mjbJ3IimPQV5CrhQ1TRPiEUKtGr085Nk5qTBoTRLxVWxXLjUQ_AawNEeL7rTx4yguDHXHVrydrnCDpuueTCqQMSd6a619i7fQz2BSRCkrUQfY1GfkH2Mx1NZ31ovidioCOAgrv2CMS-nnslFujQfmP-5yS5giPVjn0vCGw4BzOBRzQg4jBgkTZuHwfJtkbDGYdBolwX5-DOlt58PHtigAQ
