---
defaults:
  secrets_file: secrets.txt
  mqtt_port: 1883
  serial_ports: &1
  - "/dev/ttyUSB0"
  - "/dev/ttyACM0"
development:
  secrets_file: secrets.txt
  mqtt_port: 1883
  serial_ports: *1
test:
  secrets_file: secrets.txt
  mqtt_port: 1883
  serial_ports: *1
production:
  secrets_file: secrets.txt
  mqtt_port: 1883
  serial_ports:
  - "/dev/ttyUSB0"
  - "/dev/ttyACM0"
  webapp_url: http://localhost:3000/
  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE0NTkxMTU2MzIsImp0aSI6IjIyOWEwOTE0LTFmOTEtNDRkNC05YzRmLWU2ZjA3NDA1NWUxZSIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMC8iLCJleHAiOjE0NTk0NjEyMzIsIm1xdHQiOiJsb2NhbGhvc3QiLCJib3QiOiIwODIyNTk5My02NmMyLTRlZWMtYTQ3Ni0yZGJmNWE4MzVjZGQifQ.TQK2eRvKSjiJNEbgZJwXpoegAl4CVNHgnJj4eikvynkk3jsHRGv57XNnH6nccQ1kURdq9LEVeZEZRKR7XQFFszsM8XjVtg_q71qlurxzwMKs9o70cp0PmJX8qnhRlEjnftozJX1sWosfKSwf-hdHFXx-1lK3QoiN_dGowzGoyCdeVxSiQgV1u_Lg6Mu4ABC1E99140MXlkTGTfb-rGBFW7QX7CYWrHMXnqsEyWl6c6kjsO60WyhRXf3njEShFEYl8TYV6oBIWBJFf26EQICOohvsrkC_vsJMEP4_7ql8F1W_YSBeXgkfavjS75wz5j7Zp8FZbatquOAFDP7obO8-rw
  email: admin@admin.com
  token_issued_at: 1459115811
  token_id: 07778e39-f630-4f0a-bf9b-abbfc442a66a
  token_expiration: 1459461411
  mqtt_url: localhost
  device_uuid: 08225993-66c2-4eec-a476-2dbf5a835cdd
