# config/application.yml
defaults: &defaults
  secrets_file: 'secrets.txt'
  mqtt_port: 1883
  serial_ports:
    - "/dev/ttyUSB0"
    - "/dev/ttyACM0"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
